CLASS zcl_run_csv_upload DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_RUN_CSV_UPLOAD IMPLEMENTATION.
ENDCLASS.