CLASS zcl_upload_from_csv DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_UPLOAD_FROM_CSV IMPLEMENTATION.
ENDCLASS.