CLASS zcl_osapiens_sync DEFINITION
  PUBLIC
  FINAL
  CREATE PUBLIC .

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.



CLASS ZCL_OSAPIENS_SYNC IMPLEMENTATION.
ENDCLASS.